global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "offupi"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "offupi-app:8080"

  - job_name: "redis"
    static_configs:
      - targets:
          - "redis-exporter:9121"

  - job_name: "kafka"
    static_configs:
      - targets:
          - "kafka-exporter:9308"